apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: apps.banzaicloud.com
spec:
  group: banzaicloud.com
  names:
    kind: App
    listKind: AppList
    plural: apps
    singular: app
  scope: Namespaced
  version: v1alpha1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpa-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hpa-operator
  template:
    metadata:
      labels:
        name: hpa-operator
    spec:
      containers:
        - name: hpa-operator
          image: banzaicloud/hpa-operator:dev
          command:
          - hpa-operator
          imagePullPolicy: Always
