apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpa-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hpa-operator
  template:
    metadata:
      labels:
        name: hpa-operator
    spec:
      containers:
        - name: hpa-operator
          image: banzaicloud/hpa-operator:latest
          command:
          - hpa-operator
          imagePullPolicy: Always
